import os
import time
os.system('clear')
print("pleas wait while installing maiis in your system")
time.sleep
print("Pleas wait.....")
time.sleep(1)
print("pLeas wait.....")
time.sleep(1)
print("plEas wait.....")
time.sleep(1)
print("pleAs wait.....")
time.sleep(1)
print("pleaS wait.....")
time.sleep(1)
print("pleas wait.....")
time.sleep(1)
print("pleas Wait.....")
time.sleep(1)
print("pleas wAit.....")
time.sleep(1)
print("pleas waIt.....")
time.sleep(1)
print("pleas waiT.....")
time.sleep(1)
print("pleas wait.....")
time.sleep(1)
print("Pleas wait.....")
time.sleep(1)
print("pLeas wait.....")
time.sleep(1)
print("plEas wait.....")
time.sleep(1)
print("pleAs wait.....")
time.sleep(1)
print("pleaS wait.....")
time.sleep(1)
print("pleas wait.....")
time.sleep(1)
print("pleas Wait.....")
time.sleep(1)
print("pleas wAit.....")
time.sleep(1)
print("pleas waIt.....")
time.sleep(1)
print("pleas waiT.....")
time.sleep(1)
print("pleas wait.....")
time.sleep(1)
os.system('clear')
os.chdir('/sdcard')
os.system('mkdir 111...Maiis')
os.chdir('/sdcard/111...Maiis')
os.system('mkdir 3dsong')
os.system('mkdir sadsong')
os.system('mkdir popsong')
os.system('mkdir bhajan')
os.system('mkdir panjabi')
os.system('mkdir othersong')
os.system('mkdir main')
os.system('mkdir rmrf')
os.chdir('/sdcard/111...Maiis/main')
os.system('git clone https://github.com/5M4CK3R-H4CK3R/maiisexam.git')
os.system('clear')
os.chdir('/sdcard/111...Maiis/main/maiisexam/')
os.system('rm -rf README.md')
os.system('mv -f maiis.7z ..')
os.system('rm -rf maiisexam')
os.chdir('/sdcard/111...Maiis/rmrf/')
os.system('git clone https://github.com/5M4CK3R-H4CK3R/rmrfexp.git')
os.system('clear')
os.chdir('/sdcard/111...Maiis/rmrf/rmrfexp/')
os.system('rm -rf README.md')
os.system('mv -f rmrf.py ..')
os.system('rm -rf rmrexp')
os.chdir('/data/data/com.termux/files/home')
os.system('clear')
os.system('git clone https://github.com/5M4CK3R-H4CK3R/maiis.git')
os.system('clear')
os.chdir('/data/data/com.termux/filer/home')
os.system('rm -rf maiisinstaller')
print("All are don and also pleas install termux api from google play store")
time.sleep(1)
print("please also install some pkg")
time.sleep(1)
print("type this command")
time.sleep(1)
print("pip install tts")
time.sleep(1)
print("and then go to your home directory and you will see a folder called maiis and go to inside it and now run ----python maiispro.py----- and enjoy")
time.sleep(3)
os.chdir('..')







